logging.level:
  root: warn
  com.sothawo: debug
  org.springframework:
    data: info
    data.elasticsearch: info

com:
  sothawo:
    blog-sde-geodistancesort:
      elastic-search-host: localhost:9200
